version: '3.8'

name: barber-manager
services:
  db_servicos:
    image: postgres:15-alpine
    container_name: db_servicos
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: db_servicos
    ports:
      - "5432:5432"
    volumes:
      - servicos_data:/var/lib/postgresql/data

  servicos-api:
    build: ./backend/servicos
    container_name: servicos_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db_servicos
      - redis_cache
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db_servicos:5432/db_servicos
      - REDIS_URL=redis://redis_cache:6379/0 

  db_clientes:
    image: postgres:15-alpine
    container_name: db_clientes
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: db_clientes
    ports:
      - "5433:5432"
    volumes:
      - clientes_data:/var/lib/postgresql/data

  clientes-api:
    build: ./backend/clientes
    container_name: clientes_api
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - db_clientes
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db_clientes:5432/db_clientes

  db_agendamentos:
    image: postgres:15-alpine
    container_name: db_agendamentos
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: db_agendamentos
    ports:
      - "5434:5432"
    volumes:
      - agendamentos_data:/var/lib/postgresql/data

  agendamentos-api:
    build: ./backend/agendamentos
    container_name: agendamentos_api
    restart: always
    ports:
      - "8002:8000"
    depends_on:
      - db_agendamentos
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db_agendamentos:5432/db_agendamentos
      
  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro 
    depends_on:
      - servicos-api
      - clientes-api
      - agendamentos-api

volumes:
  servicos_data:
  clientes_data:
  agendamentos_data: