events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/servicos/ {
            proxy_pass http://servicos_api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/clientes/ {
            proxy_pass http://clientes_api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/agendamentos/ {
            proxy_pass http://agendamentos_api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}