name: Barber Manager CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Criar arquivo .env de teste
      run: |
        echo "DB_USER=usuario_teste" >> .env
        echo "DB_PASSWORD=senha_teste" >> .env
        echo "SECRET_KEY=chave_secreta_do_github_actions" >> .env

    - name: Validar sintaxe do Docker Compose
      run: docker compose config

    - name: Build das imagens Docker (Teste de Integração)
      run: docker compose build